### ISSUE TITLE
Using airflow.prefix value breaks deployment

### ISSUE THREAD

**Issue by rolanddb** [gsemet/kube-airflow#10]
If you pick a value other than empty string, the ENV vars in the containers will be prepended with this value (eg if you set prefix to "af_" then RABBIT_HOST becomed AF_RABBIT_HOST). This breaks nearly all Pods.

**Comment by gsemet** [comment]
Can you try with `stibbons31/kube-airflow:airflow-kube_executor_url_prefix-kube-1.6-v21` ?

Env var are injected with this configmap:
https://github.com/Stibbons/kube-airflow/blob/master/airflow/templates/configmaps-env.yaml
so the conflict should not occur (it doesn't on my setup, on our local kube cluster where I need to use this prefix to prevent conflict in my namespace)

**Comment by rolanddb** [comment]
Ok, I have tested with your docker container (set `airflow.image` to `stibbons31/kube-airflow:airflow-HEAD-patched-kube-1.6 `).

* Used a prefix 'af-'
* All Pods start up correctly and can communicate

I ssh'ed into the scheduler node and looked at the environment variables:

`airflow@af-scheduler-414841862-sltx1:~$ env | grep RAB
AF_RABBITMQ_PORT_5672_TCP_ADDR=10.0.110.217
AF_RABBITMQ_PORT_15672_TCP_ADDR=10.0.110.217
AF_RABBITMQ_SERVICE_PORT_AF_NODE=5672
AF_RABBITMQ_PORT_15672_TCP_PROTO=tcp
AF_RABBITMQ_PORT_5672_TCP=tcp://10.0.110.217:5672
AF_RABBITMQ_PORT=tcp://10.0.110.217:5672
RABBITMQ_HOST=af-rabbitmq
AF_RABBITMQ_PORT_5672_TCP_PORT=5672
RABBITMQ_CREDS=airflow:airflow
AF_RABBITMQ_PORT_15672_TCP_PORT=15672
AF_RABBITMQ_SERVICE_PORT_AF_MGNT=15672
AF_RABBITMQ_PORT_5672_TCP_PROTO=tcp
AF_RABBITMQ_PORT_15672_TCP=tcp://10.0.110.217:15672
AF_RABBITMQ_SERVICE_PORT=5672
AF_RABBITMQ_SERVICE_HOST=10.0.110.217
`
So I'm not sure if the fix will work when people use another port?
(Not that I would want to do so, I think the point of configuration should be the Kubernetes service for RabbitMQ, which can either forward to a RabbitMQ hosted in a Pod or some RabbitMQ hosted externally to the airflow namespace).

**Comment by gsemet** [comment]
yes, this is the next step. I will rewrite it all cleanly when I will propose to the official helm repository. rabbit/postgre should use the requirements.yml feature of helm, it solves it all for us. And get rid of the entrypoint.sh and so on

**Comment by rolanddb** [comment]
Ok great. Thanks for your effort.
