### ISSUE TITLE
livenessProbe for web Pod is incorrect

### ISSUE THREAD

**Issue by rolanddb** [gsemet/kube-airflow#11]
It is currently configured to:
`path: "{{ .Values.airflow.url_prefix }}/health"`

Looking at the logs of the web container, I see this:
`10.244.3.1 - - [13/Dec/2017:15:20:36 +0000] "GET /airflow/health HTTP/1.1" 404 3703 "-" "Go-http-client/1.1"`

Kubernetes then kills the Pod, and the web Pod eventually goes into a CrashLoopBackOff.

When I have changed the value to: `path: "/health"` things work as intended.

Note that is a vanilla deployment of this repo, i.e. I did not add or modify any variables.

**Comment by gsemet** [comment]
It comes from an issue in my implementation of prefix handling in airflow. I have fixed this in my version of the docker image, can you try with `stibbons31/kube-airflow:airflow-HEAD-patched-kube-1.6` (or try the label`airflow-kube_executor_url_prefix-kube-1.6-v21`)

**Comment by rolanddb** [comment]
I can confirm that the livenessProbe works correctly when I set `airflow.image` to `stibbons31/kube-airflow:airflow-HEAD-patched-kube-1.6 `.

Can you share the changes to the Dockerfile? Thanks!

**Comment by rolanddb** [comment]
A new issue with this docker image, is that the admin page blows up:

`  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'b61b92d95c363ad9464f80aa9c63d05f8f5c4f63' is not JSON serializable`

Edit: I think this was the issue: https://github.com/puckel/docker-airflow/issues/116. I cleared my cookies and the admin page works now.
