### ISSUE TITLE
Contribute to kubernetes/charts

### ISSUE THREAD

**Issue by gsemet** [gsemet/kube-airflow#15]
When this chart is mature enough, let's contribute to incubator section of kubernetes/charts

**Comment by rolanddb** [comment]
@gsemet I see that you have a fork of kubernetes/charts from which you've created a PR.

How do you migrate files from this repo (kube-airflow) to the charts repo? Just copy them over?

Our team also has a fork of kubernetes/charts. I have to add kube-airflow there as well.  So it seems to me, that we are doing things twice.

Maybe it is time, to move all the development work on this chart into the big charts repo? I think it can accelerate the final development.

**Comment by gsemet** [comment]
Yes that's planned. But I still receive interesting contributions here, so I do the copy manually from time to time. It's time consuming and inefficient, indeed.

I still [have some reviews](https://github.com/kubernetes/charts/pull/3959#pullrequestreview-106599219) on the airflow charts to fix before it be officially merged. So, I see two solutions:
- I ditch this repo, pointing to [my fork of kubernetes/charts](https://github.com/gsemet/charts/tree/airflow/incubator/airflow), so when people contribute they are all in the same repo (merge will be easier)
- or I keep on manually copy this chart to the official MR

I think I'll go the the first option so I do not have manual operations anymore. Thanks for your remark, I think I'll do what you recommend

**Comment by rolanddb** [comment]
First option sounds good to me. I have copied my fork into https://github.com/Eneco/charts/tree/feature/airflow and will continue developing there.

**Comment by gsemet** [comment]
done on https://github.com/gsemet/charts/tree/airflow/incubator/airflow

**Comment by gsemet** [comment]
@rolanddb can you rebase on https://github.com/gsemet/charts/tree/airflow/incubator/airflow I have updated a lot of code but I do not have the possibility to test for a few days. Can you look at it?

**Comment by rolanddb** [comment]
I made some changes, but the upgrade of api versions means that this charts does not run on our cluster anymore (1.8.8). I'll continue on monday.
