### ISSUE TITLE
Flower Pod goes into CrashLoopBackoff

### ISSUE THREAD

**Issue by rolanddb** [gsemet/kube-airflow#17]
kubectl get events:

`kubectl events says: spec.containers{airflow-flower}   Warning   Unhealthy   kubelet, k8s-development-41339263-2   Liveness probe failed: HTTP probe failed with statuscode: 404
`

The probe is defined as path: “{{ .Values.ingress.flower.path }}/” and the value in values.yaml is /flower

So the probe checks `localhost:5555/flower`, which returns 404. Changing the value in the values.yaml to empty string (“”) fixes the probe.

**Comment by gsemet** [comment]
yes, you need to remove "{{ .Values.ingress.flower.path }}" from the path
