### ISSUE TITLE
Location of volumeMount in Pod and dags_folder in config are out of sync

### ISSUE THREAD

**Issue by rolanddb** [gsemet/kube-airflow#20]
I installed using the default values, but enabled persistence.

A PV was dynamically created by the PVC and correctly mounted in the relevant Pods. So far so good.

However, the default location where the PV is mounted in the pods is /dags.
The value of dags_folder in airflow.cfg is pointing to /usr/local/airflow/dags.

Hence, more work is needed to use persistent volumes to store DAG files.

**Comment by rolanddb** [comment]
As a quick workaround, you can change the values of the helm chart like this:

```
  ## mount path for persistant volume
  dag_path: /usr/local/airflow/dags
```

Maybe it is enough to just change the default to this directory, and add a comment that airflow.cfg must be kept in sync. I can create a PR like this if you want.

Or remove the option to specify the mount directory altogether. Less moving parts :)

**Comment by gsemet** [comment]
can you make a pull request?

**Comment by rolanddb** [comment]
I found out that the airflow.cfg can now be overridden with environment variables.
So in the PR I added `AIRFLOW__CORE__DAGS_FOLDER: {{ .Values.airflow.dag_path }}` which keeps the configuration in sync with the mount path.

This means that the earlier change (commit) from /dags to /usr/local/airflow/dags is redundant.

**Comment by gsemet** [comment]
Yes, I have updated the puckel image so you can use this feature
