### ISSUE TITLE
Use requirements.yaml for all dependencies 

### ISSUE THREAD

**Issue by Sedward** [gsemet/kube-airflow#5]
We should consider using a requirements.yaml for RabbitMQ and Postgres and stop managing these  charts ourselves. This also allows for these dependencies to be optional. In some cases, some people may choose to run a Postgres outside their k8s cluster (such as RDS).

**Comment by gsemet** [comment]
i would make it indeed optional so users can use their own configuration.

**Comment by gsemet** [comment]
done
